name: Smart Inventory Scanner

services:
  db:
    image: mongodb:latest
  container_name: db
  ports:
    - "27017:27017"
  volumes:
    - ./data:/data/db
  healthcheck:
    test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"]
    interval: 1m30s
    timeout: 30s
    retries: 120
    start_period: 30s

  backend:
    build:
      context: ./SmartInventoryScanner
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 120
      start_period: 30s

  llm-service:
    build:
      context: ./LLM
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 120
      start_period: 30s

  frontend:
    build:
      context: ./PrettyScanner
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 120
      start_period: 30s

volumes:
  data:
