services:
  inventory:
    build:
      context: ./Inventory
      dockerfile: Dockerfile
  
  llm-service:
    build:
      context: ./LLM
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./PrettyScanner
      dockerfile: Dockerfile