apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: fivemowner/smart-inventory-reader-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@db:5432/Inventory